version: "3.8"

services:

  schedules-ui:
    build:
      context: .
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - node_modules:/app/node_modules

volumes:
  node_modules:
