name: PR Checks

on: pull_request

jobs:
  Build:
    name: PR Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Unit tests
        run: CI=true npm test
